spring:
  datasource:
    url: jdbc:mysql://localhost:3307/taskdb?createDatabaseIfNotExist=true
    username: root
    password: 12345678
    drver-class-name: com.mysql.jdbc.Driver
    application:
      name: task
