management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sample?createDatabaseIfNotExsist=true
      username: root
        password: 12345678
          driver-class-name: com.mysql.jdbc.Driver

jpa:
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop